spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Europe/Warsaw
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
api:
  key: 16209cb29ac8fa4b449f259e5b4263ce
#api.key =

#  spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/cinema_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Europe/Warsaw
#
#spring.datasource.username=root
#spring.datasource.password=root
#api.key =16209cb29ac8fa4b449f259e5b4263ce

